name: Unit Tests CI

on:
  push:
    branches: 'main'
  pull_request:
    branches: '**'

jobs:
  check-file-changes:
    uses: ./.github/workflows/check-changes.yml

  build:

    runs-on: ubuntu-latest
    needs: check-file-changes

    steps:
      - uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
        if: needs.check-file-changes.outputs.only_modified == 'false'
      - run: npm ci
        if: needs.check-file-changes.outputs.only_modified == 'false'
      - run: npm run build --if-present
        if: needs.check-file-changes.outputs.only_modified == 'false'
      - run: npm test
        if: needs.check-file-changes.outputs.only_modified == 'false'
      - name: coveralls
        uses: coverallsapp/github-action@v2
        if: needs.check-file-changes.outputs.only_modified == 'false'

