name: Unit Tests CI

on:
  push:
    branches: 'main'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: check-changes
        uses: ./.github/workflows/check-changes.yml
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
        if: steps.check-changes.outputs.changed-ignored.only_modified == 'false'
      - run: npm ci
        if: steps.check-changes.outputs.changed-ignored.only_modified == 'false'
      - run: npm run build --if-present
        if: steps.check-changes.outputs.changed-ignored.only_modified == 'false'
      - run: npm test
        if: steps.check-changes.outputs.changed-ignored.only_modified == 'false'
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: steps.check-changes.outputs.changed-ignored.only_modified == 'false'

